#通用开发环境配置

#redis配置
spring:
  redis:
    #redis 单机环境配置
    host: 192.168.128.104
    port: 6379
    password:
    database: 99
    timeout: 5000
    ssl: false
    #redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000

jpower:
  test:
    nacos:
      #      注册中心地址
      server-addr: 192.168.0.4:82
    sentinel:
      #      sentinel流控组件地址
      dashboard: 192.168.0.4:84
    seata:
      grouplist: 192.168.0.4:85
    elk:
      destination: 192.168.0.4:9000
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.8:18995/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: root